CREATE ROLE scm LOGIN PASSWORD 'cloudera';
CREATE DATABASE scm OWNER scm ENCODING 'UTF8';
CREATE ROLE rman LOGIN PASSWORD 'cloudera';
CREATE DATABASE rman OWNER rman ENCODING 'UTF8';
CREATE ROLE hue LOGIN PASSWORD 'cloudera';
CREATE DATABASE hue OWNER hue ENCODING 'UTF8';
CREATE ROLE hive LOGIN PASSWORD 'cloudera';
CREATE DATABASE metastore OWNER hive ENCODING 'UTF8';
CREATE ROLE oozie LOGIN PASSWORD 'cloudera';
CREATE DATABASE oozie OWNER oozie ENCODING 'UTF8';
CREATE ROLE das LOGIN PASSWORD 'cloudera';
CREATE DATABASE das OWNER das ENCODING 'UTF8';
CREATE ROLE schemaregistry LOGIN PASSWORD 'cloudera';
CREATE DATABASE schemaregistry OWNER schemaregistry ENCODING 'UTF8';
CREATE ROLE smm LOGIN PASSWORD 'cloudera';
CREATE DATABASE smm OWNER smm ENCODING 'UTF8';
CREATE ROLE rangeradmin LOGIN PASSWORD 'cloudera';
CREATE DATABASE ranger OWNER rangeradmin ENCODING 'UTF8';
CREATE ROLE rangerkms LOGIN PASSWORD 'cloudera';
CREATE DATABASE rangerkms OWNER rangerkms ENCODING 'UTF8';
CREATE ROLE rangerrms LOGIN PASSWORD 'cloudera';
CREATE DATABASE rangerrms OWNER rangerrms ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;
GRANT ALL PRIVILEGES ON DATABASE rangerkms TO rangerkms;
GRANT ALL PRIVILEGES ON DATABASE rangerrms TO rangerrms;
ALTER DATABASE das SET standard_conforming_strings=off; 
ALTER DATABASE oozie SET standard_conforming_strings=off; 
ALTER DATABASE hue SET standard_conforming_strings=off; 
ALTER DATABASE ranger SET standard_conforming_strings=off; 
ALTER DATABASE rangerkms SET standard_conforming_strings=off; 
ALTER DATABASE rangerrms SET standard_conforming_strings=off; 
\q